version: "2"
services:
  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./:/var/www
    links:
      - php
  php:
    build: .
    links:
      - mysql
    volumes:
      - ./:/var/www
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: humhub
      MYSQL_PASSWORD: humhub
      MYSQL_USER: humhub
